# Generated by Django 6.0.3 on 2026-04-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
