# Generated by Django 6.0.4 on 2026-04-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_series"),
    ]

    operations = [
        migrations.CreateModel(
            name="TVChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("poster_path", models.CharField(max_length=500)),
                ("stream_url", models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
